import React, {Component} from 'react';
import './App.css';
import ChallengeBig from '../challenge/ChallengeBig';

class App extends Component {
    render() {
        return (
            <div>
            <div className="row">
                <div className="col s6 m3 l2">
                    <ChallengeBig
                        title="Install solar panels"
                        image="https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/256x256/solar_panel.png"
                        reward="200 gallons of honey"
                        description="Solar panels are a great investment. They not only add value to your home, they also benefit the environment considerably, as you cut back on the amount of fossil fuels needed as an energy source. The amount of energy generated by solar panels can be sold back to the grid."
                    />
                </div>
                <div className="col s6 m3 l2">
                    <ChallengeBig
                        title="Install solar panels"
                        image="https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/256x256/solar_panel.png"
                        reward="200 gallons of honey"
                        description="Solar panels are a great investment. They not only add value to your home, they also benefit the environment considerably, as you cut back on the amount of fossil fuels needed as an energy source. The amount of energy generated by solar panels can be sold back to the grid."
                    />
                </div>
                <div className="col s6 m3 l2">
                    <ChallengeBig
                        title="Install solar panels"
                        image="https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/256x256/solar_panel.png"
                        reward="200 gallons of honey"
                        description="Solar panels are a great investment. They not only add value to your home, they also benefit the environment considerably, as you cut back on the amount of fossil fuels needed as an energy source. The amount of energy generated by solar panels can be sold back to the grid."
                    />
                </div>
                <div className="col s6 m3 l2">
                    <ChallengeBig
                        title="Install solar panels"
                        image="https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/256x256/solar_panel.png"
                        reward="200 gallons of honey"
                        description="Solar panels are a great investment. They not only add value to your home, they also benefit the environment considerably, as you cut back on the amount of fossil fuels needed as an energy source. The amount of energy generated by solar panels can be sold back to the grid."
                    />
                </div>
            </div>
        </div>
        );
    }
}

export default App;
