"""empty message

Revision ID: 104670f51d85
Revises: 89ff77846521
Create Date: 2018-06-03 13:35:38.975564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104670f51d85'
down_revision = '89ff77846521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(create_constraint=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
