"""empty message

Revision ID: 9c2558ce9bb9
Revises: 9644b3f0f3f8
Create Date: 2018-06-14 12:38:58.149771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2558ce9bb9'
down_revision = '9644b3f0f3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dares', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('dares', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dares', 'value')
    op.drop_column('dares', 'image')
    # ### end Alembic commands ###
