"""empty message

Revision ID: eb5f95dc619b
Revises: ab2faafd30a9
Create Date: 2018-06-22 14:59:46.854641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5f95dc619b'
down_revision = 'ab2faafd30a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colonymembers', type_='foreignkey')
    op.create_foreign_key(None, 'colonymembers', 'users', ['follower_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'friends', 'users', ['followed_id'], ['id'])
    op.drop_constraint(None, 'hives', type_='foreignkey')
    op.create_foreign_key(None, 'hives', 'users', ['beekeeper'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'userdares', type_='foreignkey')
    op.create_foreign_key(None, 'userdares', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'id')
    op.drop_constraint(None, 'userdares', type_='foreignkey')
    op.create_foreign_key(None, 'userdares', 'users', ['owner_id'], ['user_id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['user_id'])
    op.drop_constraint(None, 'hives', type_='foreignkey')
    op.create_foreign_key(None, 'hives', 'users', ['beekeeper'], ['user_id'])
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['follower_id'], ['user_id'])
    op.create_foreign_key(None, 'friends', 'users', ['followed_id'], ['user_id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['user_id'])
    op.drop_constraint(None, 'colonymembers', type_='foreignkey')
    op.create_foreign_key(None, 'colonymembers', 'users', ['follower_id'], ['user_id'])
    # ### end Alembic commands ###
